name: Terraform run
description: Run terraform plan/apply/destroy with common steps
inputs:
  command:
    description: "Terraform command to run: plan/apply/destroy"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.8.5"

    - name: Terraform fmt
      shell: bash
      run: terraform fmt -check

    - name: Terraform init
      shell: bash
      run: terraform init -input=false

    - name: Terraform ${{ inputs.command }}
      shell: bash
      run: |
        if [ "${{ inputs.command }}" = "plan" ]; then
          terraform plan -input=false -no-color -var-file="ci.tfvars"
        elif [ "${{ inputs.command }}" = "apply" ]; then
          terraform apply -input=false -auto-approve -var-file="ci.tfvars"
        elif [ "${{ inputs.command }}" = "destroy" ]; then
          terraform destroy -input=false -auto-approve -var-file="ci.tfvars"
        else
          echo "Unsupported command: ${{ inputs.command }}"
          exit 1
        fi
